version: "3.7"
services:
  security:
    build: ./sample-service
    ports:
      - "8123:8123"
    depends_on:
      - db
    environment:
      - DATABASE_DB=CHIRINOS
      - DATABASE_USER=root
      - DATABASE_PASSWORD=/run/secrets/db-password
      - DATABASE_HOST=db
    secrets:
      - db-password
    volumes:
      - ./sample-service/api:/app/api
    networks:
      - private
    restart: always
  db:
    build: ./database-service
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
      - ./database-service/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - private
    environment:
      - MYSQL_DATABASE=CHIRINOS
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
networks:
  private:
volumes:
  db-data:
secrets:
  db-password:
    file: database-service/password.txt
